name: pet_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  lib: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.gif
    - assets/images/logo.png
    - assets/images/petLink.png
    - assets/images/rocky.png
    - assets/images/gato.png
    - assets/images/hamster.png
    - assets/images/Amanda.png
    - assets/images/Brayan.png
    - assets/images/Fabi.png
    - assets/images/knino.png
    - assets/images/roxy.png
    - assets/images/duke.png
    - assets/images/charlie.png
    - assets/images/thor.png
    - assets/images/benny.png
    - assets/images/daisy.png
    - assets/images/bola.png
    - assets/images/uga.png
    - assets/images/leopardo.png
    - assets/images/Nayeli.png
